" Remove toolbar, menubar, scrollbars
set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L

" Try to use the system paste buffer if it's available
set guioptions+=a
set guioptions+=A

" Don't use GUI popups
set guioptions+=c

" Don't let the cursor blink ever. EVER
set guicursor=a:blinkwait0-blinkoff0-blinkon0

" Appropriate colors
hi clear CursorLineNr
hi link CursorLineNr LineNr

" Have a simple title string
set title
set titlestring=vim

" I much prefer Fira Mono
if has("macunix")
    set gfn=Fira\ Mono:h12
else
    set gfn=Fira\ Mono\ 12
endif

" Bring in machine-local customizations
if filereadable(glob("~/.gvimrc.local"))
    so ~/.gvimrc.local
endif
