" Remove toolbar, menubar, scrollbars
set go-=T
set go-=m
set go-=r
set go-=L
" Try to use the system paste buffer if it's available
set go+=a
set go+=A

" Don't let the cursor blink ever. EVER
set gcr=a:blinkwait0-blinkoff0-blinkon0

" Have a simple title string
set title
set titlestring=vim

if has("macunix")
    set gfn=Ubuntu\ Mono:h14
else
    set gfn=Ubuntu\ Mono\ 14
endif

" Add my custom match groups
hi LineTooLong gui=underline
hi TrailingWhitespace guibg=#dc322f

" Label tabs with just the filename (no path)
set guitablabel=%t

" Bring in machine-local customizations
if filereadable(glob("~/.gvimrc.local"))
    so ~/.gvimrc.local
endif
