" Remove toolbar, menubar, scrollbars
set go-=T
set go-=m
set go-=r
set go-=L
" Try to use the system paste buffer if it's available
set go+=a
set go+=A

" Don't let the cursor blink ever. EVER
set gcr=a:blinkwait0-blinkoff0-blinkon0

if has("macunix")
    set gfn=DroidSansMonoSlashed:h12,Consolas:h12
    set transparency=20
else
    set gfn=DroidSansMonoSlashed,Terminus\ 10
endif

" Use solarized colorscheme in gvim
set background=dark
colorscheme solarized

" Fix solarized a bit - this only catches some things, looks bad underlined
hi vimGroup gui=NONE

" Add my custom match groups
hi LineTooLong gui=underline
hi TrailingWhitespace guibg=red

" Label tabs with just the filename (no path)
set guitablabel=%t

" Bring in machine-local customizations
if filereadable(glob("~/.gvimrc.local"))
    so ~/.gvimrc.local
endif
