#!/usr/bin/env python
try:
    import readline
except ImportError:
    pass
else:
    import rlcompleter
    readline.parse_and_bind("tab: complete")

try:
    import warnings
    warnings.simplefilter("ignore", DeprecationWarning)
except:
    pass
