set visualbell
set textwidth=79 "should be 79
set showmatch
set showmode
set ignorecase
set backspace=2
set tabstop=4
set shiftwidth=4
set softtabstop=4
set modeline

set smartcase
set hidden
set history=1000
set scrolloff=2
set incsearch
set hlsearch

" see :help smartindent for inoremap details
set smartindent
set smarttab
set expandtab

" turn off annoying X-window title renaming
" handle window crap
set notitle
set ruler
set laststatus=2
"
set nobackup
set writebackup

:if filereadable("Jamfile")
:  set makeprg=jam
:else
:  set makeprg=bmake
:endif

" :fixdel

" xml-plugin opts before ftplugins turned on
let xml_use_html = 1

filetype plugin on

autocmd!        
syntax on
autocmd BufNewFile,BufRead *.js			so $HOME/.vim/javascript.vim|set list listchars=tab:>>
autocmd BufNewFile,BufRead *.l,*.lex		so $HOME/.vim/lex.vim
autocmd BufNewFile,BufRead *.tex		so $HOME/.vim/tex.vim
autocmd BufNewFile,BufRead *.c,*.h		so $HOME/.vim/c.vim
autocmd BufNewFile,BufRead *.cc,*.hh		so $HOME/.vim/cpp.vim
autocmd BufNewFile,BufRead *.cpp,*.hpp		so $HOME/.vim/cpp.vim
autocmd BufNewFile,BufRead *.x			so $VIMRUNTIME/syntax/rpcgen.vim
autocmd BufNewFile,BufRead *.lsp,*.lisp		so $VIMRUNTIME/syntax/lisp.vim 
autocmd BufNewFile,BufRead *.lsp,*.lisp		so $HOME/.vim/lsp.vim
autocmd BufNewFile,BufRead Make*,make*		so $HOME/.vim/Make.vim
autocmd BufNewFile,BufRead calendar		so $HOME/.vim/cal.vim
autocmd BufNewFile,BufRead mutt*,*letter*	so $HOME/.vim/mail.vim
autocmd BufNewFile,BufRead *.rsc,*.rcp		so $VIMRUNTIME/syntax/rc.vim
autocmd BufNewFile,BufRead *.*sql*,*.dump	so $HOME/.vim/sql.vim
autocmd BufNewFile,BufRead *.*sql*,*.dump	so $VIMRUNTIME/syntax/sql.vim
autocmd BufNewFile,BufRead *.php,*.inc		so $VIMRUNTIME/syntax/php.vim
autocmd BufNewFile,BufRead *.php,*.inc		so $HOME/.vim/php.vim
autocmd BufNewFile,BufRead Jam*			so $HOME/.vim/jam.vim
autocmd BufNewFile,BufRead *.pl,*.perl		so $HOME/.vim/perl.vim
autocmd BufNewFile,BufRead *.py,SConstruct	so $HOME/.vim/python.vim|set list listchars=tab:>>
autocmd BufNewFile,BufRead *.pyx,*.pxd		so $HOME/.vim/pyrex.vim
autocmd BufNewFile,BufRead *.tcl		so $HOME/.vim/tcl.vim


"	hi Comment ctermfg=5
"	hi Cursor term=reverse
"	hi clear Folded 
"	hi Folded ctermfg=DarkRed
"	hi Type ctermfg=2
"	hi Normal ctermfg=7
"


" according to smartindent help, this makes comments align as i wish
inoremap # X#

" CTRL-a does paragraph reformat
map  gqa

map  :set paste
map  :set nopaste 

map - :tabp<CR>
map = :tabn<CR>
map _ :tabc<CR>
map <C-n> :tabnew 

map <F5> :!cd /data/src/TRUNK/sls/src/python/sls && bmake local && cd /data/src/TRUNK/sls/src/python/xm && bmake local && cd /data/src/TRUNK/sls/src/python/xmui && bmake local && cd /data/src/TRUNK/sls/src/python/api && bmake local && cd /data/src/TRUNK/sls/src/ui/xm && bmake local

" http://www.vim.org/tips/tip.php?tip_id=94
set tags=tags;/

" if we're in $HOME/src/FOO/../../..., set a top level tag file of
" $HOME/src/FOO/tags
"let src = $HOME . "/src"
"let cwd = getcwd()
"if stridx(cwd, src) == 0
"  let sub = strpart(cwd, strlen(src) + 1)
"  if stridx(sub, "/") >= 0
"    let sub = strpart(sub, 0, stridx(sub, "/"))
"  endif
"  let &tags = "tags," . src . "/" . sub . "/tags"
"endif

" CTL-left does close
map O5D :fold

" CTL-right does open
map O5C :foldopen!

" set foldmethod=manual

" use my cvs .cvsrc instead of defaults
let CVSCommandDiffOpt=''

" Makes comments better color
hi Comment ctermfg=5
