# Before anything else happens, make the real directory of the config
# (where the git checkout lives) available everywhere else.
export NWGH_CONFIG_PATH="$(dirname $(dirname $(readlink ${(%):-%N})))"

# Herein lies the general config
source "${NWGH_CONFIG_PATH}/zsh/env.zsh"
source "${NWGH_CONFIG_PATH}/zsh/options.zsh"
source "${NWGH_CONFIG_PATH}/zsh/prompt.zsh"
source "${NWGH_CONFIG_PATH}/zsh/keyboard.zsh"

# Get setup that is specific to particular pieces of software that may be
# installed
for f in ${NWGH_CONFIG_PATH}/zsh/packages/* ; do
	source "$f"
done

# Some of these commands may depend on paths being set up by packages
source "${NWGH_CONFIG_PATH}/zsh/commands.zsh"

# Load OS-specific zsh configuration
case "$(uname)" in
	"Linux")
		source "${NWGH_CONFIG_PATH}/zsh/linux.zsh"
		;;
	"Darwin")
		source "${NWGH_CONFIG_PATH}/zsh/osx.zsh"
		;;
	*)
		source "${NWGH_CONFIG_PATH}/zsh/generic.zsh"
		;;
esac

# Finally, let the local machine add/override anything it wants, if it wants
if [[ -f "${HOME}/.local/zshrc" ]] ; then
    source "${HOME}/.local/zshrc"
fi
if [[ -d "${HOME}/.local/zsh.d" ]] ; then
	for f in ${HOME}/.local/zsh.d/* ; do
		source "$f"
	done
fi
if [[ -d "${HOME}/.local/bin" ]] ; then
    export PATH="${PATH}:${HOME}/.local/bin"
fi

# vim: set noexpandtab:
