PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
if [ -d /usr/local/share/python ] ; then
    PATH=/usr/local/share/python:$PATH
fi
if [ -d /usr/X11R6/bin -a ! -L /usr/X11R6/bin ] ; then
    PATH=$PATH:/usr/X11R6/bin
fi
if [ -d /usr/kerberos/bin ] ; then
    PATH=$PATH:/usr/kerberos/bin
fi
if [ -d /usr/games ] ; then
    PATH=$PATH:/usr/games
fi
if [ -d $HOME/bin ] ; then
    PATH=$PATH:$HOME/bin
fi
if [ -d /opt/local/bin ] ; then
   PATH=/opt/local/bin:/opt/local/sbin:$PATH
fi
if [ -d /todesschaf/bin ] ; then
   PATH=/todesschaf/bin:$PATH
fi
if [ -d /usr/local/cross-compile/current/bin ] ; then
    PATH=/usr/local/cross-compile/current/bin:$PATH
fi
if [ -d /opt/android/tools ] ; then
	PATH=/opt/android/tools:$PATH
fi
if [ -d /opt/android/platform-tools ] ; then
	PATH=/opt/android/platform-tools:$PATH
fi
if [ -d $HOME/.rvm/bin ] ; then
	PATH=$PATH:$HOME/.rvm/bin
fi

if [ -d /usr/local/share/man ] ; then
	MANPATH=/usr/local/share/man:$MANPATH
fi
if [ -d /opt/local/share/man ] ; then
	MANPATH=/opt/local/share/man:$MANPATH
fi
if [ -d /opt/local/share/info ] ; then
	INFOPATH=/opt/local/share/info:$INFOPATH
fi

if [ -d /opt/jetpack ] ; then
	VIRTUAL_ENV=/opt/jetpack/latest
	PATH=$PATH:$VIRTUAL_ENV/bin
	PYTHONPATH=$VIRTUAL_ENV/python-lib:$PYTHONPATH
	CUDDLEFISH_ROOT=$VIRTUAL_ENV
fi

export PATH
export MANPATH
export INFOPATH
export PYTHONPATH
export CUDDLEFISH_ROOT
export PYTHONSTARTUP=~/.pythonrc
export HISTFILE=~/.zsh_history
export HISTSIZE=500
export SAVEHIST=500
export LANG=C
export LANGUAGE=C
export PAGER=less
export RSYNC_RSH=ssh
export TZ=PST8PDT
export LESS=-FRXi
export GIT_DIFF_OPTS=--unified=8
export ANDROID_SDK=/opt/android
if [ "$TERM" = "xterm" ] ; then
	export TERM=xterm-256color
fi
if [ -f "$HOME/.mozconfig" ] ; then
	export MOZCONFIG="$HOME/.mozconfig"
fi

# vim: set noexpandtab:
