# -*- mode: sh; sh-shell: zsh -*-
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
if [ -d /usr/X11R6/bin -a ! -L /usr/X11R6/bin ] ; then
    PATH=$PATH:/usr/X11R6/bin
fi
if [ -d /usr/kerberos/bin ] ; then
    PATH=$PATH:/usr/kerberos/bin
fi
if [ -d /usr/games ] ; then
    PATH=$PATH:/usr/games
fi
if [ -d $HOME/bin ] ; then
    PATH=$PATH:$HOME/bin
    if [ -d $HOME/bin/perl ] ; then
        PATH=$PATH:$HOME/bin/perl
    fi
fi
if [ -d /opt/local/bin ] ; then
   PATH=/opt/local/bin:/opt/local/sbin:$PATH
fi
if [ -d /todesschaf/bin ] ; then
   PATH=/todesschaf/bin:$PATH
fi
if [ -d /opt/PalmSDK/Current/bin ] ; then
    PATH=/opt/PalmSDK/Current/bin:$PATH
fi
if [ -d /opt/nova/bin ] ; then
    PATH=/opt/nova/bin:$PATH
fi
if [ -d /usr/local/cross-compile/current/bin ] ; then
    PATH=/usr/local/cross-compile/current/bin:$PATH
fi
export PATH

if [ -d /opt/local/share/man ] ; then
	export MANPATH=/opt/local/share/man:$MANPATH
fi
if [ -d /opt/local/share/info ] ; then
	export INFOPATH=/opt/local/share/info:$INFOPATH
fi

if [ -d /home/palmadmin ] ; then
    export GIT_AUTHOR_EMAIL=nick.hurley@palm.com
    export GIT_COMMITTER_EMAIL=nick.hurley@palm.com
fi

export PYTHONSTARTUP=~/.pythonrc
export HISTFILE=~/.zsh_history
export HISTSIZE=500
export SAVEHIST=500
export LD_LIBRARY_PATH=/usr/local/lib
export LANG=C
export LANGUAGE=C
export PAGER=less
export RSYNC_RSH=ssh
export TZ=PST8PDT
export LESS=-Ri
if [ "$TERM" = "xterm" ] ; then
	export TERM=xterm-256color
fi
