# Herein lies the general config
source "${HOME}/.zsh.d/env.zsh"
source "${HOME}/.zsh.d/options.zsh"
source "${HOME}/.zsh.d/prompt.zsh"

# Get setup that is specific to particular pieces of software that may be
# installed
for f in ${HOME}/.zsh.d/packages/* ; do
	source "$f"
done

# Some of these commands may depend on paths being set up by packages
source "${HOME}/.zsh.d/commands.zsh"

# Load OS-specific zsh configuration
case "$(uname)" in
	"Linux")
		source "${HOME}/.zsh.d/linux.zsh"
		;;
	"Darwin")
		source "${HOME}/.zsh.d/osx.zsh"
		;;
	*)
		source "${HOME}/.zsh.d/generic.zsh"
		;;
esac

# Finally, let the local machine override anything it wants, if it wants
if [[ -f "${HOME}/.local.zsh" ]] ; then
    source "${HOME}/.local.zsh"
fi

# vim: set noexpandtab:
