# -*- mode: sh; sh-shell: zsh -*-
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

autoload -U compinit
compinit
autoload colors
colors
autoload vcs_info

# Easy-to-use colors
PR_RED="%{$fg_bold[red]%}"
PR_BLUE="%{$fg_bold[blue]%}"
PR_GREEN="%{$fg_bold[green]%}"
PR_YELLOW="%{$fg_bold[yellow]%}"
PR_RESET="%{$reset_color%}"

# vcs info config
zstyle ':vcs_info:*' enable git hg svn
zstyle ':vcs_info:*:prompt:*' formats "%r:%S"
zstyle ':vcs_info:*:prompt:*' actionformats "%r:%S:%a"
zstyle ':vcs_info:*:rprompt:*' formats "%b"
zstyle ':vcs_info:*:rprompt:*' actionformats "%b"

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
#setopt APPEND_HISTORY
## for sharing history between zsh processes
#setopt INC_APPEND_HISTORY
#setopt SHARE_HISTORY

## never ever beep ever
#setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
#MAILCHECK=0
setopt NO_AUTO_REMOVE_SLASH
setopt BSD_ECHO
setopt AUTO_PUSHD
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME
setopt NO_CORRECT
setopt NO_CORRECT_ALL
setopt AUTO_CD

# Prompt and such
setopt prompt_subst

function make_prompt {
	vcs_info prompt

	if [[ -n "$vcs_info_msg_0_" ]] ; then
		repo="$(echo "$vcs_info_msg_0_" | cut -d: -f1)"
		rpath="$(echo "$vcs_info_msg_0_" | cut -d: -f2 | sed -e 's/^\./\//')"
		act="$(echo "$vcs_info_msg_0_" | cut -d: -f3)"
		rval="$PR_GREEN$repo$PR_RESET:$PR_BLUE$rpath$PR_RESET"
		if [[ -n "$act" ]] ; then
			rval="$rval$PR_RED($act)$PR_RESET"
		fi
	else
		rval="%n@%m:%~"
	fi

	echo "$rval"
}

function make_rprompt {
	vcs_info rprompt
	if [[ -n "$vcs_info_msg_0_" ]] ; then
		echo "$PR_YELLOW($vcs_info_msg_0_)$PR_RESET"
	else
		echo ""
	fi
}

export PROMPT="\$(make_prompt)%(!.#.$) "
export RPROMPT="\$(make_rprompt)"

alias sdiff="${HOME}/bin/sdiff"

case "$(uname)" in
	"Linux")
		source "${HOME}/.zshrc_linux"
		;;
	"Darwin")
		source "${HOME}/.zshrc_osx"
		;;
	*)
		source "${HOME}/.zshrc_generic"
		;;
esac
